// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nipzxdtimtxwbymnfnka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pcHp4ZHRpbXR4d2J5bW5mbmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDYyMjksImV4cCI6MjA1ODcyMjIyOX0.oh7JhiKWsbCJXKXpIb2OUq1oN5ImjpQP74RunnN0ne4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);