// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyudjhtcbqzajimjgytf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5dWRqaHRjYnF6YWppbWpneXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDk0MDQsImV4cCI6MjA1ODgyNTQwNH0.5J02C40d0vvL-sxlW0zXM6XBH-UwlNmS-R0c1EsOYGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);